### ISSUE TITLE
default_analysis.py terminates if database is empty

### ISSUE THREAD

**Issue by mcanul** [UHMC/landmark-analysis#2]
cursor.fetchone() causes the default_analysis.py to terminate if the cursor is devoid of items after a query. To fix, a check must be done before calling fetchone() to make sure the query did not return an empty set.

**Comment by knight7** [comment]
This also prevents the demo instructions from working (an instructional workaround is currently impractical -- prioritize fixing this issue).

**Comment by mcanul** [comment]
Commit: d50c2ea61cc65741655989c92f4042331b02ec8b

```Traceback (most recent call last):
  File "default_analysis.py", line 113, in <module>
    last_entry = int(cursor.fetchone()[0])
TypeError: 'NoneType' object has no attribute '__getitem__'
```
Occurs in line 113 after database is cleared after being initially populated.

**Comment by knight7** [comment]
Commit: d50c2ea61cc65741655989c92f4042331b02ec8b
Running default analysis with empty database (necessary for demo and intended functionality):
```default_analysis.py 
Traceback (most recent call last):
  File "default_analysis.py", line 58, in <module>
    last_entry = int(cursor.fetchone()[0])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by knight7** [comment]
Problem source identified as attempting to access zeroth index of cursor.fetchone()'s returned object.

```Python
result=cursor.fetchone()
updated_result=result[0]
last_entry = int(updated_result)
```

```Python
Traceback (most recent call last):
  File "default_analysis.py", line 59, in <module>
    updated_result=result[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```
